---
- name: deploy | prerequisites
  hosts: all
  become: yes
  become_user: robotenemy
  vars:
    site_dir: /home/robotenemy/www/robotenemy.com
  tasks:
    - name: create site folder (if needed)
      file:
        path: "{{ site_dir }}"
        state: directory
    - name: clone repo
      git:
        repo: "https://github.com/delameko/robotenemy.git"
        dest: "{{ site_dir }}"

